apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bg-app
      version: blue
  template:
    metadata:
      labels:
        app: bg-app
        version: blue
    spec:
      containers:
        - name: blue-container
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bg-app
      version: green
  template:
    metadata:
      labels:
        app: bg-app
        version: green
    spec:
      containers:
        - name: green-container
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bg-service
spec:
  selector:
    app: bg-app
    #version: blue
    version: green
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bg-ingress
spec:
  rules:
    - host: bg-app.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bg-service
                port:
                  number: 80
