apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-webserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-webserver
spec:
  containers:
    - name: webserver
      image: nginx
      volumeMounts:
        - name: webserver-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: webserver-volume
      persistentVolumeClaim:
        claimName: pvc-webserver
        readOnly: false
  restartPolicy: Always
---

