apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-secret
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: db-secret-vol
