apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http-web
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - name: http-web  
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: myapp-nodeport-service
#spec:
#  selector:
#    app: myapp
#  ports:  
#  - protocol: TCP
#    port: 80
#    targetPort: 80
#    nodePort: 30007
#  type: NodePort
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: myapp-loadbalancer-service
#spec:
#  selector:
#    app: myapp
#  ports:  
#  - protocol: TCP
#    port: 80
#    targetPort: 80
#  type: LoadBalancer
#
#
