apiVersion: v1
kind: Pod
metadata:
  name: sec-pod
spec:
  containers:
    - name: sec-container
      image: mariadb
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MARIADB_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MARIADB_PASSWORD

